import "./globals.css";
import { Inter } from "next/font/google";
import React from "react";
import Link from "next/link";

const inter = Inter({ weight: ["400", "700"], subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </head>
      <body className={inter.className}>
        <header>
          <h1>{metadata.title}</h1>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/blog">Blog</Link>
          </nav>
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
